apiVersion: apps/v1
kind: Deployment
metadata:
  name: meshcentral-deployment
  annotations:
    argocd-image-updater.argoproj.io/image-list: meshcentral=docker.io/dselen/meshcentral
    argocd-image-updater.argoproj.io/meshcentral.image-name: docker.io/dselen/meshcentral
spec:
  replicas: 5
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: meshcentral
  template:
    metadata:
      labels:
        app: meshcentral
    spec:
      containers:
      - name: meshcentral
        image: docker.io/dselen/meshcentral:latest
        ports:
        - containerPort: 443
